name: "3DPrinter-OctoPrint"
version: "2022.6.028"
slug: "3dprinter-octoprint"
description: "New instance of OctoPrint"
url: "https://github.com/fredrikbaberg/home-assistant-addons/tree/main/3dprinter-octoprint"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
stage: experimental
init: false
map:
  - share:rw
ports:
  5000/tcp: 5000
ingress: true
image: ghcr.io/fredrikbaberg/addon-camera-aiortc-{arch}
