name: "3DPrinter-OctoPrint"
version: "2022.6.010"
slug: "3dprinter-octoprint"
description: "New instance of OctoPrint"
url: "https://github.com/fredrikbaberg/home-assistant-addons/tree/main/3dprinter-octoprint"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
ports:
  5000/tcp: null
