name: "3DPrinter-OP"
version: "2022.7.018"
slug: "3dprinter-op"
description: "OctoPrint as an addon, no additional bells and whistles."
url: "https://github.com/fredrikbaberg/home-assistant-addons/tree/main/3dprinter-op"
ingress: true
ingress_stream: true
panel_icon: mdi:printer-3d
panel_title: 3DPrinter-OP
arch:
    - armv7
    - amd64
    - armhf
    - aarch64
    - i386
stage: experimental
init: false
realtime: true
gpio: true
uart: true
usb: true
ports:
    5000/tcp: null
ports_description:
    5000/tcp: Web-based interface (Not required for Ingress)
options:
    recovery: false
schema:
    recovery: "bool"
image: ghcr.io/fredrikbaberg/addon-3dprinter-octoprint-{arch}
tmpfs: true
